import type { Metadata } from "next"
import { type ReactNode } from "react"
import { Footer, Header } from "@/components/widgets"
import { geist, jaro, staatliches } from "./fonts"
import "@/styles/reset.scss"
import "@/styles/general.scss"

export const metadata: Metadata = {
	title: "Veloce",
	description: "Generated by create next app"
}

const RootLayout = ({ children }: Readonly<{ children: ReactNode }>) => {
	return (
		<html id="html" lang="en">
			<body
				className={`${jaro.variable} ${geist.variable} ${staatliches.variable}`}
			>
				<Header />

				{children}

				<Footer />
			</body>
		</html>
	)
}

export default RootLayout
